# Generated by Django 4.0.1 on 2022-02-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_hobby_reunion_person_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='asunto',
            field=models.CharField(max_length=100, verbose_name='Asunto de Reunion'),
        ),
    ]
